env:
  global:
    - PKG_BUILD="library/packages"
    - ARCHIVES_TMP="/tmp/archives"
    - REGISTRY_URL="docker.index"
    - PROJECT_NAME="galmido-host"
    - IMAGE_FLAVOR="http/server"
    - IMAGE_PREFIX="tengine"
    - CONFIGURE="build.args"
  matrix:
    - VERSION="2.0.0"
    - VERSION="2.0.1"
    - VERSION="2.0.2"
    - VERSION="2.0.3"
install:
  - sudo sh -c "echo Dpkg::Options {'--force-confold'} >> /etc/apt/apt.conf"
  - sudo apt-get update && sudo apt-get upgrade && sudo apt-get dist-upgrade
  - sudo apt-get install build-essential dpkg-dev -y --no-install-recommends
  - curl -sSL https://get.docker.com/ubuntu/ | sudo sh
script:
  - mkdir -p "$ARCHIVES_TMP" && cp -r sources "$ARCHIVES_TMP"
  - tar zxf "sources/tengine-$VERSION.tar.gz" -C "$ARCHIVES_TMP"
  - cp -r "$PKG_BUILD/$VERSION" "$ARCHIVES_TMP/tengine-$VERSION"
  - cd "$ARCHIVES_TMP/tengine-$VERSION" && dpkg-buildpackage -b
  - cp -p "$ARCHIVES_TMP/*.deb" "$TRAVIS_BUILD_DIR/packages"



